In [1]:
# ---------------------------------------------------------------------------------------------------------------------
# sys
import sys
# ---------------------------------------------------------------------------------------------------------------------
# system
from math import sqrt, ceil
# ---------------------------------------------------------------------------------------------------------------------
# scientific
import numpy as np
# ---------------------------------------------------------------------------------------------------------------------
# PyQuantum.TC_Lindblad
from PyQuantum.TC_Lindblad.Cavity import Cavity
from PyQuantum.TC_Lindblad.Hamiltonian3 import Hamiltonian3

from PyQuantum.TC_Lindblad.WaveFunction import WaveFunction
from PyQuantum.TC_Lindblad.DensityMatrix import DensityMatrix

from PyQuantum.TC_Lindblad.Evolution import run_out_click

import PyQuantum.TC_Lindblad.config as config
# ---------------------------------------------------------------------------------------------------------------------
# PyQuantum.Tools
from PyQuantum.Tools.LoadPackage import load_pkg
from PyQuantum.Tools.Assert import *
from PyQuantum.Tools.Print import hr
from PyQuantum.Tools.MkDir import *
from PyQuantum.Tools.CSV import *
from PyQuantum.Tools.Units import *
from PyQuantum.Tools.Pickle import *
from copy import copy
# ---------------------------------------------------------------------------------------------------------------------
# PyQuantum.Common
from PyQuantum.Common.Quantum.Operators import operator_a, operator_across
# ---------------------------------------------------------------------------------------------------------------------

In [4]:
config.capacity = 4
config.n_atoms = 1
config.n_levels = 3

cavity = Cavity(wc=config.wc, wa=config.wa, g=config.g,
                n_atoms=config.n_atoms, n_levels=config.n_levels)

cavity.info()

H = Hamiltonian3(config.capacity, cavity)

H.iprint()
H.df
# H.print_states()

# s_3 = WaveFunction(states=H.states, init_state=[1, [0, 1, 2]], amplitude=1./sqrt(6)) + \
#     WaveFunction(states=H.states, init_state=[1, [1, 2, 0]], amplitude=1./sqrt(6)) + \
#     WaveFunction(states=H.states, init_state=[1, [2, 0, 1]], amplitude=1./sqrt(6)) - \
#     WaveFunction(states=H.states, init_state=[1, [1, 0, 2]], amplitude=1./sqrt(6)) - \
#     WaveFunction(states=H.states, init_state=[1, [2, 1, 0]], amplitude=1./sqrt(6)) - \
#     WaveFunction(states=H.states, init_state=[
#                  1, [0, 2, 1]], amplitude=1./sqrt(6))

# t_0 = WaveFunction(states=H.states, init_state=[1, [0, 0, 0]])

# t_0.print()

Cavity:

wc: 6.729 GHz

wa: 6.729 GHz

 g: 67.29 MHz

 n_atoms: 1

 n_levels: 3

[[0 1 0]
 [0 0 2]
 [0 0 0]]
[[0 0 0]
 [1 0 0]
 [0 2 0]]
[[0 0 0]
 [0 1 0]
 [0 0 4]]
[0, [0]]
[0, [1]]
[0, [2]]
[1, [0]]
[1, [1]]
[1, [2]]
[2, [0]]
[2, [1]]
[2, [2]]
[3, [0]]
[3, [1]]
[4, [0]]
4
[0, [0]]
[0, [1]]
[0, [2]]
[1, [0]]
[1, [1]]
[1, [2]]
[2, [0]]
[2, [1]]
[2, [2]]
[3, [0]]
[3, [1]]
[4, [0]]


[0, [0]]   [0, [1]]    [0, [2]]   [1, [0]]    [1, [1]]     [1, [2]]  \
[0, [0]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz       0.0 Hz   
[0, [1]]   0.0 Hz  6.729 GHz      0.0 Hz  67.29 MHz      0.0 Hz       0.0 Hz   
[0, [2]]   0.0 Hz     0.0 Hz  26.916 GHz     0.0 Hz  134.58 MHz       0.0 Hz   
[1, [0]]   0.0 Hz  67.29 MHz      0.0 Hz  6.729 GHz      0.0 Hz       0.0 Hz   
[1, [1]]   0.0 Hz     0.0 Hz  134.58 MHz     0.0 Hz  13.458 GHz       0.0 Hz   
[1, [2]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz   33.645 GHz   
[2, [0]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz  95.162 MHz       0.0 Hz   
[2, [1]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz  190.325 MHz   
[2, [2]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz       0.0 Hz   
[3, [0]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz       0.0 Hz   
[3, [1]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz       0.0 Hz   
[4, [0]]   0.0 Hz     0.0 Hz      0.0 Hz     0.0 Hz      0.0 Hz       0.0 Hz   

            [2, [0]]     [2, [1]]     [2, [2]]    [3, [0]]     [3, [1]]  \
[0, [0]]      0.0 Hz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[0, [1]]      0.0 Hz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[0, [2]]      0.0 Hz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[1, [0]]      0.0 Hz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[1, [1]]  95.162 MHz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[1, [2]]      0.0 Hz  190.325 MHz       0.0 Hz      0.0 Hz       0.0 Hz   
[2, [0]]  13.458 GHz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   
[2, [1]]      0.0 Hz   20.187 GHz       0.0 Hz  116.55 MHz       0.0 Hz   
[2, [2]]      0.0 Hz       0.0 Hz   40.374 GHz      0.0 Hz  233.099 MHz   
[3, [0]]      0.0 Hz   116.55 MHz       0.0 Hz  20.187 GHz       0.0 Hz   
[3, [1]]      0.0 Hz       0.0 Hz  233.099 MHz      0.0 Hz   26.916 GHz   
[4, [0]]      0.0 Hz       0.0 Hz       0.0 Hz      0.0 Hz       0.0 Hz   

            [4, [0]]  
[0, [0]]      0.0 Hz  
[0, [1]]      0.0 Hz  
[0, [2]]      0.0 Hz  
[1, [0]]      0.0 Hz  
[1, [1]]      0.0 Hz  
[1, [2]]      0.0 Hz  
[2, [0]]      0.0 Hz  
[2, [1]]      0.0 Hz  
[2, [2]]      0.0 Hz  
[3, [0]]      0.0 Hz  
[3, [1]]      0.0 Hz  
[4, [0]]  47.103 GHz